models.py
from database import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.VARCHAR(50), nullable=False, unique=True)
    email = db.Column(db.VARCHAR(100), nullable=False, unique=True)
    password = db.Column(db.VARCHAR, nullable=False)


class University(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.VARCHAR(50), nullable=False, unique=True)
    short_description = db.Column(db.VARCHAR(600), nullable=False, unique=True)

class Feedback(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.VARCHAR(600), nullable=False, unique=True)
    university = db.Column(db.Text, db.ForeignKey('university.name'), nullable=False)


class Teachers(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.VARCHAR(50), nullable=False, unique=True)
    short_description = db.Column(db.VARCHAR(600), nullable=False, unique=True)
    university = db.Column(db.Text, db.ForeignKey('university.name'), nullable=False)

app.py
from flask import Flask
from config import Configuration
#from database import db
from universities.blueprint import feedbacks

app = Flask(__name__)
app.config.from_object(Configuration)

#with app.app_context():
   # db.create_all()


app.register_blueprint(feedbacks, url_prefix='/unic')

main.py
from app import app
import views
# from database import db

if __name__ == "__main__":
    app.run()

universities/blueprint.py
from flask import Blueprint
from flask import render_template

feedbacks = Blueprint("feedbacks", __name__, template_folder='templates')


@feedbacks.route('/')
def index():
    return render_template('feedbacks/index.html')

views.py
from app import app
from flask import render_template

@app.route('/')
def index():
    return render_template('index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block name %}


        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-inverse bg-inverse">
    <div class="container-fluid">
        <a class="navbar-brand" href=" {{ url_for('feedbacks.index') }} ">Main</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Account</a>
                </li>

            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <h1>
            {% block content_title %}


            {% endblock %}
        </h1>

        {% block content %}


        {% endblock %}
    </div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block name %}
KFU
{%  endblock %}
{% block content_title %}
KFU unic
<link rel="stylesheet" href="base.css">

<nav id="navbar-example3" class="navbar navbar-light bg-light flex-column align-items-stretch p-3">
    <a class="navbar-brand" href="#">Feedback on</a>
    <nav class="nav nav-pills flex-column">
        <a class="nav-link" href="#item-1">Institute</a>
        <nav class="nav nav-pills flex-column">
            <a class="nav-link ms-3 my-1" href="#item-1-1">Example 1</a>
            <a class="nav-link ms-3 my-1" href="#item-1-2">Example 2</a>
        </nav>
        <a class="nav-link" href="#item-2">Teachers</a>
        <a class="nav-link" href="#item-3">Вormitory</a>
        <nav class="nav nav-pills flex-column">
            <a class="nav-link ms-3 my-1" href="#item-3-1">Example 3</a>
            <a class="nav-link ms-3 my-1" href="#item-3-2">Example 4</a>
        </nav>
    </nav>
</nav>

<div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-offset="0" tabindex="0">
    <h4 id="item-1">Institute</h4>
    <p></p>
    <h5 id="item-1-1">Example 1</h5>
    <p>...</p>
    <h5 id="item-1-2">Example 2</h5>
    <p>...</p>
    <h4 id="item-2">Teachers</h4>
    <p>...</p>
    <h4 id="item-3">Вormitory</h4>
    <p>...</p>
    <h5 id="item-3-1">Example 3</h5>
    <p>...</p>
    <h5 id="item-3-2">Example 4</h5>
    <p>...</p>
</div>
{%  endblock %}
{% block content %}
35
{%  endblock %}